name: Build hospital app and deploy to aliyun
on:
  #监听push操作
  push:
    branches:
      # master分支，你也可以改成其他分支
      - master
jobs:
  build:
    # runs-on 指定job任务运行所需要的虚拟机环境(必填字段)
    runs-on: ubuntu-latest
    steps:
      # 获取源码
      - name: Checkout
        # 使用action库  actions/checkout获取源码
        uses: actions/checkout@master
      # 安装Node13
      - name: use Node.js 12.16.0
        # 使用action库  actions/setup-node安装node
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.0
      # 安装依赖
      - name: yarn install
        run: yarn install
      # 打包
      - name: yarn build
        run: yarn run deploy
      # 部署到阿里云
      - name: Deploy to Aliyun Backend
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          # 私钥
          SSH_PRIVATE_KEY: ${{ secrets.JDH_SECRET }}
          # scp参数
          ARGS: "-avzr --delete"
          # 源目录，编译后生成的文件目录
          SOURCE: "packages/hospital-backend/releases"
          # 服务器ip：换成你的服务器IP
          REMOTE_HOST: "47.100.45.189"
          # 用户
          REMOTE_USER: "root"
          # 目标地址 你在服务器上部署代码的地方
          TARGET: "/root/app/hospital/backend"
      # 部署到阿里云
      - name: Deploy to Aliyun Frontend
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          # 私钥
          SSH_PRIVATE_KEY: ${{ secrets.JDH_SECRET }}
          # scp参数
          ARGS: "-avzr --delete"
          # 源目录，编译后生成的文件目录
          SOURCE: "packages/hospital-frontend/build"
          # 服务器ip：换成你的服务器IP
          REMOTE_HOST: "47.100.45.189"
          # 用户
          REMOTE_USER: "root"
          # 目标地址 你在服务器上部署代码的地方
          TARGET: "/root/app/hospital/frontend"
